<?xml version="1.0"?>
<package format="3">
  <name>macrobot_description</name>
  <version>0.4.0</version>
  <description>Reviewed full-visual and reduced kinematic descriptions for MacRobot with D435F and gripper.</description>
  <maintainer email="dyddl2082@snu.ac.kr">Kim Jinhyeong</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher_gui</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>macrobot_arm_kinematics</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
