from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Dict, Optional, Tuple

from ament_index_python.packages import get_package_share_directory
import rclpy
from rclpy.node import Node
from sensor_msgs.msg import JointState
from std_msgs.msg import Float64, String

from .safety import SafeRegionGrid, SafetyValidator, ValidationResult
from .servo_mapping import JOINT_NAMES, load_servo_mapping


Q = Tuple[float, float, float]


class IKValidatorNode(Node):
    """Gate IK and direct joint goals before they can reach the servo bridge.

    The node validates both the endpoint and the complete straight joint-space
    interpolation from the last commanded state. This matches the trajectory
    generated by :class:`ArmServoBridgeNode`.
    """

    def __init__(self) -> None:
        super().__init__("macrobot_ik_validator")

        safe_pkg = Path(get_package_share_directory("macrobot_safe_region"))
        default_actuator_file = safe_pkg / "config" / "actuator_limits.yaml"

        self.declare_parameter("ik_solution_topic", "/macrobot/arm/ik_solution")
        self.declare_parameter("direct_goal_topic", "/macrobot/arm/joint_goal")
        self.declare_parameter("gripper_target_topic", "/macrobot/gripper/target")
        self.declare_parameter("current_state_topic", "/macrobot/arm/logical_joint_states")
        self.declare_parameter("validated_goal_topic", "/macrobot/arm/validated_joint_goal")
        self.declare_parameter("status_topic", "/macrobot/arm/validation_status")
        self.declare_parameter("rejected_goal_topic", "/macrobot/arm/rejected_joint_goal")

        self.declare_parameter("actuator_limits_file", str(default_actuator_file))
        self.declare_parameter("safe_region_csv", "")
        self.declare_parameter("require_safe_region", False)
        self.declare_parameter("safe_region_mode", "cell")
        self.declare_parameter("required_safe_region_revision", "macrobot-serial-2axis-2026-09-04-r4")
        self.declare_parameter("path_step_rad", math.radians(1.0))
        self.declare_parameter("max_goal_delta_rad", 3.2)

        actuator_file = str(self.get_parameter("actuator_limits_file").value)
        self.mapping = load_servo_mapping(actuator_file)
        self.require_safe_region = bool(self.get_parameter("require_safe_region").value)
        safe_csv = str(self.get_parameter("safe_region_csv").value).strip()
        grid: Optional[SafeRegionGrid] = None
        if safe_csv:
            try:
                grid = SafeRegionGrid(safe_csv)
                self.get_logger().info(
                    f"Loaded connected safe-region grid: {grid.path} "
                    f"({len(grid.samples)} samples)"
                )
                required_revision = str(
                    self.get_parameter("required_safe_region_revision").value
                ).strip()
                if required_revision and grid.model_revision != required_revision:
                    raise RuntimeError(
                        "Safe-region model revision mismatch: "
                        f"required={required_revision!r}, found={grid.model_revision!r}, "
                        f"summary={grid.summary_path}"
                    )
            except Exception as exc:
                if self.require_safe_region:
                    raise RuntimeError(f"Safe-region loading failed: {exc}") from exc
                self.get_logger().warning(
                    f"Safe-region unavailable; analytic validation only: {exc}"
                )
        elif self.require_safe_region:
            raise RuntimeError("require_safe_region=true but safe_region_csv is empty")
        else:
            self.get_logger().warning(
                "No safe_region_csv configured; using analytic and actuator limits only."
            )

        self.validator = SafetyValidator(
            self.mapping,
            grid,
            str(self.get_parameter("safe_region_mode").value),
        )
        self.path_step_rad = float(self.get_parameter("path_step_rad").value)
        self.max_goal_delta_rad = float(self.get_parameter("max_goal_delta_rad").value)
        self.current_q: Q = self.mapping.logical_limits.home

        self.validated_pub = self.create_publisher(
            JointState, str(self.get_parameter("validated_goal_topic").value), 10
        )
        self.rejected_pub = self.create_publisher(
            JointState, str(self.get_parameter("rejected_goal_topic").value), 10
        )
        self.status_pub = self.create_publisher(
            String, str(self.get_parameter("status_topic").value), 10
        )

        self.create_subscription(
            JointState,
            str(self.get_parameter("ik_solution_topic").value),
            lambda msg: self._handle_goal(msg, "ik_solution"),
            10,
        )
        self.create_subscription(
            JointState,
            str(self.get_parameter("direct_goal_topic").value),
            lambda msg: self._handle_goal(msg, "direct_joint_goal"),
            10,
        )
        self.create_subscription(
            Float64,
            str(self.get_parameter("gripper_target_topic").value),
            self._gripper_target_callback,
            10,
        )
        self.create_subscription(
            JointState,
            str(self.get_parameter("current_state_topic").value),
            self._current_state_callback,
            10,
        )

        self.get_logger().info(
            "IK validator ready: raw IK/direct goals -> /macrobot/arm/validated_joint_goal"
        )

    @staticmethod
    def _extract_q(msg: JointState, fallback: Q) -> Optional[Q]:
        values: Dict[str, float] = dict(zip(msg.name, msg.position))
        if not values:
            return None
        result = tuple(values.get(name, fallback[index]) for index, name in enumerate(JOINT_NAMES))
        if not all(math.isfinite(value) for value in result):
            return None
        return result  # type: ignore[return-value]

    def _current_state_callback(self, msg: JointState) -> None:
        q = self._extract_q(msg, self.current_q)
        if q is not None:
            self.current_q = q

    def _gripper_target_callback(self, msg: Float64) -> None:
        goal = JointState()
        goal.header.stamp = self.get_clock().now().to_msg()
        goal.name = list(JOINT_NAMES)
        goal.position = [self.current_q[0], self.current_q[1], float(msg.data)]
        self._handle_goal(goal, "gripper_target")

    def _handle_goal(self, msg: JointState, source: str) -> None:
        goal = self._extract_q(msg, self.current_q)
        if goal is None:
            self._reject(msg, source, ValidationResult(False, "invalid_joint_state_message"))
            return

        if max(abs(goal[i] - self.current_q[i]) for i in range(3)) > self.max_goal_delta_rad:
            self._reject(
                msg,
                source,
                ValidationResult(
                    False,
                    "goal_delta_too_large",
                    {"current": list(self.current_q), "goal": list(goal)},
                ),
            )
            return

        result = self.validator.validate_path(
            self.current_q, goal, self.path_step_rad
        )
        if not result.ok:
            self._reject(msg, source, result)
            return

        output = JointState()
        output.header.stamp = self.get_clock().now().to_msg()
        output.name = list(JOINT_NAMES)
        output.position = list(goal)
        self.validated_pub.publish(output)
        self._publish_status(
            True,
            "goal_validated",
            {
                "source": source,
                "current": list(self.current_q),
                "goal": list(goal),
                **result.details,
                "safe_region_loaded": self.validator.safe_grid is not None,
            },
        )

    def _reject(self, msg: JointState, source: str, result: ValidationResult) -> None:
        self.rejected_pub.publish(msg)
        self._publish_status(
            False,
            "goal_rejected",
            {
                "source": source,
                "reason": result.reason,
                "current": list(self.current_q),
                **result.details,
            },
        )

    def _publish_status(self, ok: bool, event: str, details: Dict[str, object]) -> None:
        payload = {"ok": ok, "event": event, **details}
        message = String()
        message.data = json.dumps(payload, ensure_ascii=False)
        self.status_pub.publish(message)
        if ok:
            self.get_logger().info(message.data)
        else:
            self.get_logger().warning(message.data)


def main(args=None) -> None:
    rclpy.init(args=args)
    node = IKValidatorNode()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        if rclpy.ok():
            rclpy.shutdown()


if __name__ == "__main__":
    main()
