"""Analytic and sampled safe-region validation for the MacRobot arm."""

from __future__ import annotations

from bisect import bisect_left
import csv
from dataclasses import dataclass, field
import itertools
import math
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Set, Tuple

import yaml

from .servo_mapping import ServoMapping


Q = Tuple[float, float, float]


@dataclass(frozen=True)
class ValidationResult:
    ok: bool
    reason: str
    details: Dict[str, object] = field(default_factory=dict)


class AnalyticValidator:
    def __init__(self, mapping: ServoMapping) -> None:
        self.mapping = mapping

    def validate(self, q: Q) -> ValidationResult:
        q1, q2, q3 = (float(v) for v in q)
        if not all(math.isfinite(v) for v in (q1, q2, q3)):
            return ValidationResult(False, "non_finite_joint_value")

        limits = self.mapping.logical_limits
        if not (limits.q1_min <= q1 <= limits.q1_max):
            return ValidationResult(False, "q1_logical_limit", {"q1": q1})
        if not (limits.q2_min <= q2 <= limits.q2_max):
            return ValidationResult(False, "q2_logical_limit", {"q2": q2})
        if not (limits.q3_min <= q3 <= limits.q3_max):
            return ValidationResult(False, "q3_logical_limit", {"q3": q3})

        rear_lift_angle = q1 + q2
        if not (limits.tool_pitch_min <= rear_lift_angle <= limits.tool_pitch_max):
            return ValidationResult(
                False, "rear_lift_angle_limit", {"rear_lift_angle": rear_lift_angle}
            )
        toggle_bound = math.pi / 2.0 - limits.four_bar_margin_rad
        if abs(q2) > toggle_bound:
            return ValidationResult(
                False,
                "four_bar_toggle_margin",
                {"q2": q2, "allowed_abs_max": toggle_bound},
            )

        servo_ok, servo_reason = self.mapping.command_limits_ok(q1, q2, q3)
        commands = self.mapping.servo_commands_deg(q1, q2, q3)
        if not servo_ok:
            return ValidationResult(False, servo_reason, {"servo_deg": commands})
        return ValidationResult(
            True,
            "safe",
            {
                "rear_lift_angle": rear_lift_angle,
                "servo_deg": commands,
                "servo_pulse_us": self.mapping.servo_pulses_us(q1, q2, q3),
            },
        )


class SafeRegionGrid:
    """Connected safe samples generated by ``macrobot_safe_region``.

    ``cell`` mode is conservative: a continuous query is accepted only when
    every grid corner surrounding it is in the home-connected safe component.
    ``nearest`` mode accepts the nearest connected sample within half a grid
    diagonal and is mainly useful for coarse visualization/debugging.
    """

    def __init__(self, csv_path: str | Path) -> None:
        self.path = Path(csv_path).expanduser().resolve()
        if not self.path.exists():
            raise FileNotFoundError(f"Safe-region CSV not found: {self.path}")

        rows: List[Q] = []
        with self.path.open("r", encoding="utf-8", newline="") as stream:
            reader = csv.DictReader(stream)
            required = {"q1_rad", "q2_rad", "q3_rad"}
            if not required.issubset(set(reader.fieldnames or [])):
                raise ValueError(
                    f"Safe-region CSV is missing columns {sorted(required)}: {self.path}"
                )
            for row in reader:
                if "connected" in row and str(row["connected"]).strip() not in ("1", "true", "True"):
                    continue
                rows.append(
                    (float(row["q1_rad"]), float(row["q2_rad"]), float(row["q3_rad"]))
                )
        if not rows:
            raise ValueError(f"Safe-region CSV has no connected samples: {self.path}")

        self.q1_values = sorted({q[0] for q in rows})
        self.q2_values = sorted({q[1] for q in rows})
        self.q3_values = sorted({q[2] for q in rows})
        self.samples: Set[Tuple[float, float, float]] = {
            self._key(q) for q in rows
        }
        self.steps = (
            self._median_step(self.q1_values),
            self._median_step(self.q2_values),
            self._median_step(self.q3_values),
        )
        self.summary_path = self.path.parent / "safe_region_summary.yaml"
        self.model_revision: Optional[str] = None
        if self.summary_path.exists():
            with self.summary_path.open("r", encoding="utf-8") as stream:
                summary = yaml.safe_load(stream) or {}
            value = summary.get("model_revision")
            if value is not None:
                self.model_revision = str(value)

    @staticmethod
    def _key(q: Sequence[float]) -> Tuple[float, float, float]:
        return tuple(round(float(value), 9) for value in q)  # type: ignore[return-value]

    @staticmethod
    def _median_step(values: Sequence[float]) -> float:
        if len(values) < 2:
            return math.inf
        differences = sorted(
            b - a for a, b in zip(values[:-1], values[1:]) if b - a > 1e-12
        )
        if not differences:
            return math.inf
        return differences[len(differences) // 2]

    @staticmethod
    def _bracket(values: Sequence[float], x: float, eps: float = 1e-8) -> Optional[List[float]]:
        if x < values[0] - eps or x > values[-1] + eps:
            return None
        index = bisect_left(values, x)
        if index < len(values) and abs(values[index] - x) <= eps:
            return [values[index]]
        if index == 0 or index == len(values):
            return None
        return [values[index - 1], values[index]]

    def validate(self, q: Q, mode: str = "cell") -> ValidationResult:
        mode = mode.lower().strip()
        if mode == "nearest":
            return self._validate_nearest(q)
        if mode != "cell":
            return ValidationResult(False, "unknown_safe_region_mode", {"mode": mode})

        brackets = [
            self._bracket(self.q1_values, q[0]),
            self._bracket(self.q2_values, q[1]),
            self._bracket(self.q3_values, q[2]),
        ]
        if any(item is None for item in brackets):
            return ValidationResult(
                False,
                "outside_sampled_safe_region_bounds",
                {"q": list(q)},
            )

        for axis_index, bracket in enumerate(brackets):
            assert bracket is not None
            if len(bracket) == 2:
                step = self.steps[axis_index]
                if not math.isinf(step) and (bracket[1] - bracket[0]) > 1.5 * step:
                    return ValidationResult(
                        False,
                        "safe_region_grid_gap",
                        {
                            "axis": axis_index,
                            "lower": bracket[0],
                            "upper": bracket[1],
                            "nominal_step": step,
                        },
                    )

        missing: List[List[float]] = []
        for corner in itertools.product(*brackets):  # type: ignore[arg-type]
            if self._key(corner) not in self.samples:
                missing.append([float(v) for v in corner])
        if missing:
            return ValidationResult(
                False,
                "unsafe_or_boundary_safe_region_cell",
                {"q": list(q), "missing_corner_count": len(missing), "first_missing": missing[0]},
            )
        return ValidationResult(True, "safe_region_cell", {"q": list(q)})

    def _validate_nearest(self, q: Q) -> ValidationResult:
        nearest = (
            min(self.q1_values, key=lambda value: abs(value - q[0])),
            min(self.q2_values, key=lambda value: abs(value - q[1])),
            min(self.q3_values, key=lambda value: abs(value - q[2])),
        )
        if self._key(nearest) not in self.samples:
            return ValidationResult(False, "nearest_sample_not_connected", {"nearest": nearest})
        tolerances = tuple(
            math.inf if math.isinf(step) else step * 0.51 for step in self.steps
        )
        distances = tuple(abs(a - b) for a, b in zip(q, nearest))
        if any(distance > tolerance for distance, tolerance in zip(distances, tolerances)):
            return ValidationResult(
                False,
                "too_far_from_connected_sample",
                {"nearest": nearest, "distance": distances, "tolerance": tolerances},
            )
        return ValidationResult(
            True,
            "safe_region_nearest",
            {"nearest": nearest, "distance": distances},
        )


class SafetyValidator:
    def __init__(
        self,
        mapping: ServoMapping,
        safe_grid: Optional[SafeRegionGrid] = None,
        grid_mode: str = "cell",
    ) -> None:
        self.analytic = AnalyticValidator(mapping)
        self.safe_grid = safe_grid
        self.grid_mode = grid_mode

    def validate_point(self, q: Q) -> ValidationResult:
        analytic = self.analytic.validate(q)
        if not analytic.ok:
            return analytic
        if self.safe_grid is None:
            return analytic
        sampled = self.safe_grid.validate(q, self.grid_mode)
        if not sampled.ok:
            return sampled
        details = dict(analytic.details)
        details.update(sampled.details)
        return ValidationResult(True, "safe", details)

    def validate_path(self, start: Q, goal: Q, max_step_rad: float) -> ValidationResult:
        max_step_rad = max(1e-6, float(max_step_rad))
        largest_delta = max(abs(b - a) for a, b in zip(start, goal))
        count = max(1, int(math.ceil(largest_delta / max_step_rad)))
        for index in range(count + 1):
            t = index / count
            q = tuple(a + t * (b - a) for a, b in zip(start, goal))  # type: ignore[assignment]
            result = self.validate_point(q)
            if not result.ok:
                details = dict(result.details)
                details.update({"path_index": index, "path_samples": count + 1, "path_t": t, "q": list(q)})
                return ValidationResult(False, result.reason, details)
        return ValidationResult(
            True,
            "safe_path",
            {"path_samples": count + 1, "start": list(start), "goal": list(goal)},
        )
