"""Serial two-axis MacRobot arm kinematics.

Generated by migrate_four_bar_to_serial2r.py from the active URDF.
The public logical names remain arm_lift_joint, wrist_pitch_joint and
 gripper_joint, but q2 is now an independent wrist coordinate. No arm
four-bar closure or q1+q2 actuator coupling is used.
"""

from __future__ import annotations

from dataclasses import dataclass
import math
from typing import List, Optional, Sequence, Tuple

Vec3 = Tuple[float, float, float]
Mat3 = Tuple[Tuple[float, float, float], Tuple[float, float, float], Tuple[float, float, float]]


def normalize_angle(angle: float) -> float:
    return math.atan2(math.sin(angle), math.cos(angle))


def _dot(a: Vec3, b: Vec3) -> float:
    return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]


def _add(a: Vec3, b: Vec3) -> Vec3:
    return (a[0] + b[0], a[1] + b[1], a[2] + b[2])


def _sub(a: Vec3, b: Vec3) -> Vec3:
    return (a[0] - b[0], a[1] - b[1], a[2] - b[2])


def _scale(v: Vec3, scale: float) -> Vec3:
    return (v[0] * scale, v[1] * scale, v[2] * scale)


def _cross(a: Vec3, b: Vec3) -> Vec3:
    return (
        a[1] * b[2] - a[2] * b[1],
        a[2] * b[0] - a[0] * b[2],
        a[0] * b[1] - a[1] * b[0],
    )


def _norm(v: Vec3) -> float:
    return math.sqrt(_dot(v, v))


def _normalized(v: Vec3) -> Vec3:
    length = _norm(v)
    if length <= 1e-12:
        raise ValueError(f"Zero-length vector: {v}")
    return _scale(v, 1.0 / length)


def _mat_mul(a: Mat3, b: Mat3) -> Mat3:
    return tuple(
        tuple(sum(a[i][k] * b[k][j] for k in range(3)) for j in range(3))
        for i in range(3)
    )  # type: ignore[return-value]


def _mat_vec(matrix: Mat3, vector: Vec3) -> Vec3:
    return tuple(
        sum(matrix[i][k] * vector[k] for k in range(3)) for i in range(3)
    )  # type: ignore[return-value]


def _rpy_matrix(rpy: Vec3) -> Mat3:
    roll, pitch, yaw = rpy
    cr, sr = math.cos(roll), math.sin(roll)
    cp, sp = math.cos(pitch), math.sin(pitch)
    cy, sy = math.cos(yaw), math.sin(yaw)
    rx: Mat3 = ((1.0, 0.0, 0.0), (0.0, cr, -sr), (0.0, sr, cr))
    ry: Mat3 = ((cp, 0.0, sp), (0.0, 1.0, 0.0), (-sp, 0.0, cp))
    rz: Mat3 = ((cy, -sy, 0.0), (sy, cy, 0.0), (0.0, 0.0, 1.0))
    return _mat_mul(_mat_mul(rz, ry), rx)


def _axis_angle(axis: Vec3, angle: float) -> Mat3:
    x, y, z = _normalized(axis)
    c, s, t = math.cos(angle), math.sin(angle), 1.0 - math.cos(angle)
    return (
        (t * x * x + c, t * x * y - s * z, t * x * z + s * y),
        (t * x * y + s * z, t * y * y + c, t * y * z - s * x),
        (t * x * z - s * y, t * y * z + s * x, t * z * z + c),
    )


def _matrix_to_quaternion(matrix: Mat3) -> Tuple[float, float, float, float]:
    trace = matrix[0][0] + matrix[1][1] + matrix[2][2]
    if trace > 0.0:
        scale = math.sqrt(trace + 1.0) * 2.0
        qw = 0.25 * scale
        qx = (matrix[2][1] - matrix[1][2]) / scale
        qy = (matrix[0][2] - matrix[2][0]) / scale
        qz = (matrix[1][0] - matrix[0][1]) / scale
    elif matrix[0][0] > matrix[1][1] and matrix[0][0] > matrix[2][2]:
        scale = math.sqrt(1.0 + matrix[0][0] - matrix[1][1] - matrix[2][2]) * 2.0
        qw = (matrix[2][1] - matrix[1][2]) / scale
        qx = 0.25 * scale
        qy = (matrix[0][1] + matrix[1][0]) / scale
        qz = (matrix[0][2] + matrix[2][0]) / scale
    elif matrix[1][1] > matrix[2][2]:
        scale = math.sqrt(1.0 + matrix[1][1] - matrix[0][0] - matrix[2][2]) * 2.0
        qw = (matrix[0][2] - matrix[2][0]) / scale
        qx = (matrix[0][1] + matrix[1][0]) / scale
        qy = 0.25 * scale
        qz = (matrix[1][2] + matrix[2][1]) / scale
    else:
        scale = math.sqrt(1.0 + matrix[2][2] - matrix[0][0] - matrix[1][1]) * 2.0
        qw = (matrix[1][0] - matrix[0][1]) / scale
        qx = (matrix[0][2] + matrix[2][0]) / scale
        qy = (matrix[1][2] + matrix[2][1]) / scale
        qz = 0.25 * scale
    length = math.sqrt(qx * qx + qy * qy + qz * qz + qw * qw)
    return (qx / length, qy / length, qz / length, qw / length)


def _matrix_to_rpy(matrix: Mat3) -> Vec3:
    sin_pitch = max(-1.0, min(1.0, -matrix[2][0]))
    pitch = math.asin(sin_pitch)
    if abs(math.cos(pitch)) > 1e-9:
        roll = math.atan2(matrix[2][1], matrix[2][2])
        yaw = math.atan2(matrix[1][0], matrix[0][0])
    else:
        roll = math.atan2(-matrix[1][2], matrix[1][1])
        yaw = 0.0
    return (roll, pitch, yaw)


def _wrapped_values(angle: float, lower: float, upper: float) -> List[float]:
    output: List[float] = []
    for turns in range(-2, 3):
        candidate = angle + 2.0 * math.pi * turns
        if lower - 1e-9 <= candidate <= upper + 1e-9:
            output.append(candidate)
    return output


@dataclass(frozen=True)
class ArmGeometry:
    shoulder_origin_xyz: Vec3 = (0.03, 0.0937, 0.0579)
    shoulder_origin_rpy: Vec3 = (-1.662703, -1.570796, -3.049686)
    shoulder_axis: Vec3 = (-0, 0, -1)
    wrist_origin_xyz: Vec3 = (0.161, 0.0004, 0)
    wrist_origin_rpy: Vec3 = (-0, -1.570796, 0)
    wrist_axis: Vec3 = (-1, 0, 0)
    grasp_origin_xyz: Vec3 = (0.013, 0.218151, -0.008098)
    grasp_origin_rpy: Vec3 = (0, 0, 0)
    gripper_open_gap_m: float = 0.070
    gripper_closed_gap_m: float = 0.010


@dataclass(frozen=True)
class JointLimits:
    arm_lift_min: float = -1
    arm_lift_max: float = 1
    wrist_pitch_min: float = -1.3
    wrist_pitch_max: float = 1.3
    gripper_min: float = 0
    gripper_max: float = 1.5707963268

    def contains(self, q1: float, q2: float, q3: float = 0.0) -> bool:
        return (
            self.arm_lift_min <= q1 <= self.arm_lift_max
            and self.wrist_pitch_min <= q2 <= self.wrist_pitch_max
            and self.gripper_min <= q3 <= self.gripper_max
        )


@dataclass(frozen=True)
class ToolPose2D:
    """Backward-compatible name for the full 3D tool pose."""

    x: float
    y: float
    z: float
    roll: float
    pitch: float
    yaw: float
    qx: float
    qy: float
    qz: float
    qw: float


@dataclass(frozen=True)
class IKSolution:
    q1: float
    q2: float
    position_error: float
    seed_distance: float
    plane_error_m: float = 0.0
    in_plane_error_m: float = 0.0


class MacRobotArmModel:
    """Exact URDF-based planar serial 2R kinematics."""

    def __init__(
        self,
        geometry: ArmGeometry = ArmGeometry(),
        limits: JointLimits = JointLimits(),
        max_plane_error_m: float = 0.030,
        ik_tolerance_m: float = 1e-5,
    ) -> None:
        self.geometry = geometry
        self.limits = limits
        self.max_plane_error_m = max(0.0, float(max_plane_error_m))
        self.ik_tolerance_m = max(1e-8, float(ik_tolerance_m))

        g = geometry
        self._r_shoulder_origin = _rpy_matrix(g.shoulder_origin_rpy)
        self._r_wrist_origin = _rpy_matrix(g.wrist_origin_rpy)
        self._r_grasp_origin = _rpy_matrix(g.grasp_origin_rpy)
        self._normal = _normalized(_mat_vec(self._r_shoulder_origin, g.shoulder_axis))

        r_wrist_zero = _mat_mul(self._r_shoulder_origin, self._r_wrist_origin)
        wrist_axis_base = _normalized(_mat_vec(r_wrist_zero, g.wrist_axis))
        alignment = _dot(self._normal, wrist_axis_base)
        if abs(alignment) < 0.999:
            raise ValueError(
                "Serial 2R solver requires parallel arm axes; "
                f"axis dot product is {alignment:.9f}"
            )
        self._wrist_axis_sign = 1.0 if alignment >= 0.0 else -1.0

        v1 = _mat_vec(self._r_shoulder_origin, g.wrist_origin_xyz)
        v2 = _mat_vec(r_wrist_zero, g.grasp_origin_xyz)
        self._normal_offset = _dot(v1, self._normal) + _dot(v2, self._normal)
        v1_planar = _sub(v1, _scale(self._normal, _dot(v1, self._normal)))
        v2_planar = _sub(v2, _scale(self._normal, _dot(v2, self._normal)))
        self._l1 = _norm(v1_planar)
        self._l2 = _norm(v2_planar)
        if self._l1 <= 1e-8 or self._l2 <= 1e-8:
            raise ValueError("Degenerate serial 2R link geometry")
        self._e1 = _scale(v1_planar, 1.0 / self._l1)
        self._e2 = _normalized(_cross(self._normal, self._e1))
        self._beta = math.atan2(_dot(v2_planar, self._e2), _dot(v2_planar, self._e1))
        self._nominal_y = self.forward(0.0, 0.0, 0.0).y

    @property
    def arm_plane_normal(self) -> Vec3:
        return self._normal

    @property
    def wrist_axis_sign(self) -> float:
        return self._wrist_axis_sign

    def gripper_link_transform(self, q1: float, q2: float) -> Tuple[Vec3, Mat3]:
        g = self.geometry
        r1 = _mat_mul(self._r_shoulder_origin, _axis_angle(g.shoulder_axis, q1))
        wrist_position = _add(g.shoulder_origin_xyz, _mat_vec(r1, g.wrist_origin_xyz))
        r2 = _mat_mul(
            _mat_mul(r1, self._r_wrist_origin),
            _axis_angle(g.wrist_axis, q2),
        )
        return wrist_position, r2

    def forward(self, q1: float, q2: float, q3: float = 0.0) -> ToolPose2D:
        del q3  # grasp_nominal is fixed to gripper_link in the active URDF.
        position, rotation = self.gripper_link_transform(q1, q2)
        position = _add(position, _mat_vec(rotation, self.geometry.grasp_origin_xyz))
        rotation = _mat_mul(rotation, self._r_grasp_origin)
        roll, pitch, yaw = _matrix_to_rpy(rotation)
        qx, qy, qz, qw = _matrix_to_quaternion(rotation)
        return ToolPose2D(position[0], position[1], position[2], roll, pitch, yaw, qx, qy, qz, qw)

    def inverse_xyz(
        self,
        x: float,
        y: float,
        z: float,
        seed: Optional[Tuple[float, float]] = None,
        seed_weight: float = 0.001,
        gripper_q: float = 0.0,
        max_plane_error_m: Optional[float] = None,
    ) -> List[IKSolution]:
        if not self.limits.gripper_min <= gripper_q <= self.limits.gripper_max:
            return []
        rel = _sub((float(x), float(y), float(z)), self.geometry.shoulder_origin_xyz)
        normal_component = _dot(rel, self._normal)
        plane_error = normal_component - self._normal_offset
        allowed_plane_error = self.max_plane_error_m if max_plane_error_m is None else max(0.0, float(max_plane_error_m))
        if abs(plane_error) > allowed_plane_error:
            return []

        target_u = _dot(rel, self._e1)
        target_v = _dot(rel, self._e2)
        radius_sq = target_u * target_u + target_v * target_v
        cosine_delta = (radius_sq - self._l1 * self._l1 - self._l2 * self._l2) / (2.0 * self._l1 * self._l2)
        if cosine_delta < -1.0 - 1e-9 or cosine_delta > 1.0 + 1e-9:
            return []
        cosine_delta = max(-1.0, min(1.0, cosine_delta))
        delta_abs = math.acos(cosine_delta)

        solutions: List[IKSolution] = []
        seen = set()
        for delta in (delta_abs, -delta_abs):
            q1_base = math.atan2(target_v, target_u) - math.atan2(
                self._l2 * math.sin(delta),
                self._l1 + self._l2 * math.cos(delta),
            )
            q2_base = (delta - self._beta) / self._wrist_axis_sign
            for q1 in _wrapped_values(q1_base, self.limits.arm_lift_min, self.limits.arm_lift_max):
                for q2 in _wrapped_values(q2_base, self.limits.wrist_pitch_min, self.limits.wrist_pitch_max):
                    if not self.limits.contains(q1, q2, gripper_q):
                        continue
                    key = (round(q1, 10), round(q2, 10))
                    if key in seen:
                        continue
                    seen.add(key)
                    pose = self.forward(q1, q2, gripper_q)
                    error_vector = (pose.x - x, pose.y - y, pose.z - z)
                    in_plane_error = math.hypot(_dot(error_vector, self._e1), _dot(error_vector, self._e2))
                    if in_plane_error > max(1e-4, self.ik_tolerance_m * 10.0):
                        continue
                    position_error = _norm(error_vector)
                    seed_distance = 0.0 if seed is None else math.hypot(
                        normalize_angle(q1 - seed[0]),
                        normalize_angle(q2 - seed[1]),
                    )
                    solutions.append(
                        IKSolution(
                            q1=q1,
                            q2=q2,
                            position_error=position_error,
                            seed_distance=seed_distance,
                            plane_error_m=plane_error,
                            in_plane_error_m=in_plane_error,
                        )
                    )
        solutions.sort(
            key=lambda item: (
                item.in_plane_error_m + seed_weight * item.seed_distance,
                abs(item.plane_error_m),
                item.seed_distance,
            )
        )
        return solutions

    def inverse(
        self,
        x: float,
        z: float,
        seed: Optional[Tuple[float, float]] = None,
        seed_weight: float = 0.001,
        gripper_q: float = 0.0,
    ) -> List[IKSolution]:
        """Compatibility wrapper for callers that still provide only X/Z."""
        return self.inverse_xyz(x, self._nominal_y, z, seed, seed_weight, gripper_q)

    def gripper_gap(self, q3: float) -> float:
        limits = self.limits
        if limits.gripper_max <= limits.gripper_min:
            return self.geometry.gripper_open_gap_m
        ratio = (q3 - limits.gripper_min) / (limits.gripper_max - limits.gripper_min)
        ratio = min(1.0, max(0.0, ratio))
        blend = math.cos(0.5 * math.pi * ratio)
        return self.geometry.gripper_closed_gap_m + (
            self.geometry.gripper_open_gap_m - self.geometry.gripper_closed_gap_m
        ) * blend

    @staticmethod
    def full_visual_joint_positions(
        q1: float,
        q2: float,
        q3: float = 0.0,
        lift_servo_multiplier: float = 1.0,
        tilt_servo_multiplier: float = 1.0,
        gripper_servo_multiplier: float = 2.0,
    ) -> dict[str, float]:
        """Compatibility mapping with independent q2; no arm passive joints."""
        return {
            "arm_lift_joint": q1,
            "wrist_pitch_joint": q2,
            "gripper_joint": q3,
            "lift_servo": lift_servo_multiplier * q1,
            "tilt_servo": tilt_servo_multiplier * q2,
            "gripper_servo": gripper_servo_multiplier * q3,
            "gripper_left_gear": -q3,
            "gripper_right_gear": q3,
            "gripper_left_addition": -q3,
            "gripper_right_addition": q3,
            "gripper_left_clamp": q3,
            "gripper_right_clamp": -q3,
        }
