macrobot_mock_perception:
  ros__parameters:
    base_frame: base_link
    default_object_name: Buds3
    point_x: -0.15
    point_y: 0.0645
    point_z: 0.12
    score: 0.95
    noise_std_m: 0.0015
    publish_rate_hz: 10.0
    activation_delay_sec: 0.5
